### ISSUE TITLE
Runes preview

### ISSUE THREAD

**Issue by ThePridestalker** [jaeha-choi/DFF#1]
Hello, first of all, nice project, scrapping op.gg and saving changes to league was a nice idea. I have tried Blitz and Porofessor but both are giving you the highest winrate build, which is bad in champs that are not what proplayers play.

Now straight to the point, I noticed some problems:
- If all runepages are used,  instead of using one by default (the last one or the first one, or even the one I had selected) it will just not work and not specify the error in the debug.
- The runepages names in the program are shown with the initials (took me a bit to figure it out), but anyways, the real problem is that there is no way of visualize them if I dont open the runepage in league, and since there are normally 4 runepages classified in 2 sections: The most used runes and the highest winrates, and inside those, 2 of them, if i dont get the percentages in the names (percentages info with the number of games played is usually usefull info so you dont pick a high winrate with low quantity of games played, which is probably not a good build), or a preview, its superhard to know which one i want to play (which in my case is the most common build with highest pickrate)
Noticed that the most common highest pickrate should be the first runepage that appears selected bu default, but a preview or pickrate winrate in the name would be cool if the preview is too much!

I dont know if you are busy with IRL job and wont update the project, but fixing those 2 problems and making maybe 2 .exe files so 1 has a console and the other one doesnt, would make it perfect!

**Comment by jaeha-choi** [comment]
Thanks for the feedback!

I have updated DFF to reflect changes. I haven't tested the program thoroughly, but everything seems to be working 😃

Previews of runes would be cool. My only concern is the legality of using rune images from Riot. If I get more feedback about this, I'll send an email to Riot asking about the copyright issue. But for now, hopefully the pick rate, win rate, and sample size are enough.

The "best" build is used by default, which seems to be the most common build with the highest pick rate.

I'll close this issue but feel free to open another one if you have any comments or questions.
