### ISSUE TITLE
SSL certificate of ddragon.leagueoflegends.com failing

### ISSUE THREAD

**Issue by ThePridestalker** [jaeha-choi/DFF#2]
Hi there, today the app doesnt work at all. In the debugging version you can see the error for half a second, and I recorded a small video to check what it was about, and it fails here,
https://github.com/jaeha-choi/DFF/blob/a874c91e0fb16b63286ac8a65bee5863a778167c/main.go#L1249

The SSL certificate is down, so the http lib of Go returns an error.

If you access "http://ddragon.leagueoflegends.com/api/versions.json" (notice the http without the s) it should work, and not return an error next year when their certificate is down again.

Also if you can somehow make the error not to close the debugging terminal, or save the error to a file for future errors, it would be great!

**Comment by jaeha-choi** [comment]
Okay, I've updated the URL to use HTTP for now.

I'm thinking of re-writing a good chunk of this project as I've noticed I wasn't following the best practices at the time. I'm planning on making major changes, so stay tuned!
