### ISSUE TITLE
Error while retrieving item page

### ISSUE THREAD

**Issue by ThePridestalker** [jaeha-choi/DFF#4]
Im using version 0.6.1, error happens after selecting a champ. I have only tested in URF but probably happens in any game mode.

Logs:
core.go:806: DEBUG:	Using cache: false
core.go:815: INFO:	        ULTRA RAPID FIRE MODE IS ON!!!
core.go:926: ERROR:	Error while retrieving item page

Also happens with old versions of the app, so might opgg have changed something?

**Comment by jaeha-choi** [comment]
Yup. I just checked and opgg has updated their website.

Seems like they're providing JSON formatted data with the new design, which is quite helpful. I'll try to update it ASAP.

**Comment by jaeha-choi** [comment]
I was able to update DFF to fix the issue.

It's still in the testing phase, but try out [the beta version](https://github.com/jaeha-choi/DFF/releases/tag/v0.6.2-beta1) if you feel brave!

**Comment by ThePridestalker** [comment]
I have tested it already in urf aram and summoners rift, and no errors so far!

**Comment by jaeha-choi** [comment]
Thanks for testing DFF! Everything looks good to me, just merged to the main branch.
